name: Test

on:
  workflow_dispatch:
  pull_request_target:
    types: [ opened, synchronize ] #Runs on PR creation/updation
    branches: [ main ]
        
jobs: 
  version:
    name: Check mergeability and increment version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup github-actions bot git identity
        uses: qoomon/actions--setup-git@v1
        with:
            user: bot

      - name: Bump version
        run: |
          # Get current version before bumping
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"
          
          # Calculate what the new version will be (manual increment)
          MAJOR=$(echo $CURRENT_VERSION | cut -d '.' -f 1)
          MINOR=$(echo $CURRENT_VERSION | cut -d '.' -f 2)
          PATCH=$(echo $CURRENT_VERSION | cut -d '.' -f 3)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          echo "New version will be: $NEW_VERSION"
          
          # Check if the new version tag already exists and delete it
          if git rev-parse "v$NEW_VERSION" >/dev/null 2>&1; then
            echo "Tag v$NEW_VERSION already exists. Deleting it."
            git tag -d "v$NEW_VERSION"
          else
            echo "Tag v$NEW_VERSION does not exist. Proceeding."
          fi
          
          # Now run the actual version bump
          npm version patch

          

          