name: Test

on:
  workflow_dispatch:
  pull_request_target:
    types: [ opened, synchronize ] #Runs on PR creation/updation
    branches: [ main ]
        
jobs: 
  version:
    name: Check mergeability and increment version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup github-actions bot git identity
        uses: qoomon/actions--setup-git@v1
        with:
            user: bot

      - name: Bump version
        run: |
          npm version patch

          

          